config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:property_name, :unit_name, :tenant_name, :security_deposit_amount, :security_deposit_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/_leftnavbar.html.erb
<div class= "sidebar">
  <div class="row">
    <div class="col-2">
      <div class="list-group span2 fill" id="list-tab" role="tablist">
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">DASHBOARD</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">LEASING</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">PROPERTIES</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">PEOPLE</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">ACCOUNTING</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">MAINTENANCE</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">REPORTING</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">COMMUNICATION</a>
        <a class="list-group-item list-group-item-action left-navbar dropdown-toggle" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">WHAT'S NEW</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light background">
  <a class="navbar-brand" href="#">
    <%= image_tag("appfolio_logo.png") %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <form class="form-inline my-3 my-lg-0 ml-auto">
      <input class="form-control mr-sm-2 home-search" type="search" placeholder="Search" aria-label="Search">
      <%= button_tag type: :submit, class: "btn text-background" do %>
          <%= fa_icon 'search 1x' %>
        <% end %>
    </form>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Help & Training
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Get Help</a>
          <a class="dropdown-item" href="#">Visit User Community</a>
          <a class="dropdown-item" href="#">Make a Suggestion</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Kyle Zimmerman
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">My Settings</a>
          <a class="dropdown-item" href="#">General Settings</a>
          <a class="dropdown-item" href="#">Log Out</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityDepositTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/leftnavbar' %>
    <div class="content">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field mt-3">
    <%= form.label :security_deposit_amount %>
    <%= form.text_field :security_deposit_amount %>
  </div>

  <div class="field mt-3">
    <%= form.label :security_deposit_type %>
    <%= form.select :security_deposit_type, ['Management Held', 'Owner Held'] %>
  </div>

  <div>
    <%= form.submit class: "btn background text mt-3" %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<div class="container">
<div class= "row justify-content-center ml-5 mt-5">
<div class= "card col-10 text-center">
<h1>Edit Tenant Security Deposit</h1>


<%= render 'form', tenant: @tenant %>

<div class="mt-2">
  <%= link_to 'Back', tenants_path %>
</div>
</div>
</div>
</div>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class= "col align-self-center">
      <h1>Edit Tenants Security Deposits</h1>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Property name</th>
        <th>Unit name</th>
        <th>Tenant name</th>
        <th>Security deposit amount</th>
        <th>Security deposit type</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @tenants.each do |tenant| %>
        <tr>
          <td><%= tenant.property_name %></td>
          <td><%= tenant.unit_name %></td>
          <td><%= tenant.tenant_name %></td>
          <td><%= tenant.security_deposit_amount %></td>
          <td><%= tenant.security_deposit_type %></td>
          <td><%= link_to 'Edit', edit_tenant_path(tenant), class: "btn background text" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<div class="container col-12 text-center">
<p class="alert alert-success mt-2" id="notice"><%= notice %></p>
</div>


<div class="container">
<div class= "row justify-content-center ml-5 mt-5">
<div class= "card col-10 text-center">
<p>
  <strong>Property name:</strong>
  <%= @tenant.property_name %>
</p>

<p>
  <strong>Unit name:</strong>
  <%= @tenant.unit_name %>
</p>

<p>
  <strong>Tenant name:</strong>
  <%= @tenant.tenant_name %>
</p>

<p>
  <strong>Security deposit amount:</strong>
  <%= @tenant.security_deposit_amount %>
</p>

<p>
  <strong>Security deposit type:</strong>
  <%= @tenant.security_deposit_type %>
</p>

<p>
<%= link_to 'Edit', edit_tenant_path(@tenant), class: "btn background text" %>
<%= link_to 'Done', tenants_path, class: "btn background text" %>
</p>
</div>
</div>
</div>